print( "  _______    " )
print( " /       \\  " )
print( "/         \\ " )
print( "\\         / " )
print( " \\_______/  " )
print( "\\         / " )
print( " \\_______/  " )
print( " +-------+   " )
print( "             " )
print( "  _______    " )
print( " /       \\  " )
print( "/         \\ " )
print( "|  STOP   |  " )
print( "\\         / " )
print( " \\_______/  " )
print( "             " )
print( "  _______    " )
print( " /       \\  " )
print( "/         \\ " )
print( "+---------+  " )

