print( "   /\\   " )
print( "  /  \\  " )
print( " /    \\ " )
print( " \\    / " )
print( "  \\  /  " )
print( "   \\/   " )
print( "         " )
print( " \\    / " )
print( "  \\  /  " )
print( "   \\/   " )
print( "   /\\   " )
print( "  /  \\  " )
print( " /    \\ " )
print( "         " )
print( "   /\\   " )
print( "  /  \\  " )
print( " /    \\ " )
print( "+------+ " )
print( "|      | " )
print( "|      | " )
print( "+------+ " )
print( "| ECU  | " )
print( "|      | " )
print( "+------+ " )
print( "|      | " )
print( "|      | " )
print( "+------+ " )
print( "   /\\   " )
print( "  /  \\  " )
print( " /    \\ " )
